language: php
dist: bionic
sudo: false

matrix:
  include:
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/lumen-framework:7.*
    - php: 7.3
      env: FRAMEWORK_VERSION=laravel/lumen-framework:7.*
    - php: 7.4
      env: FRAMEWORK_VERSION=laravel/lumen-framework:7.*

install:
  - composer require "${FRAMEWORK_VERSION}" --no-update -n
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script: vendor/bin/phpunit
